[build]
  command = "yarn build"
  functions = "functions"
  publish = "dist"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200